# Generated by Django 4.0.4 on 2023-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('sessionNumber', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('response', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
