# Generated by Django 4.2.7 on 2024-01-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=False, max_length=255, null=True, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('year_of_birth', models.CharField(blank=True, max_length=4, null=True)),
                ('is_an_group_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('is_agripreneur', models.CharField(blank=True, default='Yes', max_length=255, null=True)),
                ('is_vendor', models.CharField(blank=True, default='No', max_length=255, null=True)),
                ('physical_address', models.TextField(blank=True, max_length=255, null=True)),
                ('primary_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_phone_number_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_phone_number_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_sys_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.ward')),
            ],
        ),
    ]
