# Generated by Django 4.2.7 on 2024-01-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='group_member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.AlterField(
            model_name='loanreminder',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.AlterField(
            model_name='membertraining',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_agripreneur',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes')], default='Yes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_an_group_admin',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes')], default='No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_birth',
            field=models.IntegerField(blank=True, default=1990, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.profile'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
