# Generated by Django 4.2.7 on 2024-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_profile_email_alter_groupmembers_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_sys_admin',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes')], default='False', max_length=255, null=True),
        ),
    ]
