# Generated by Django 4.2.7 on 2024-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_profile_year_of_birth_profile_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='value_chain_level',
            field=models.CharField(blank=True, choices=[('PRODUCTION', 'Production'), ('AGGREGATION', 'Agregation'), ('DISTRIBUTOR', 'Distributor'), ('FARM SERVICES', 'Farm Services'), ('INPUT DISTRIBUTOR', 'Input Disttibutor'), ('PRODUCTION', 'Production'), ('VALUE ADDITION', 'Value Addition')], max_length=255, null=True),
        ),
    ]
