# Generated by Django 4.2.7 on 2024-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_vendor_value_chain_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('COOPERATIVE', 'Coperative'), ('GENERAL FARMING', 'General Farming'), ('OTHERS', 'Others'), ('PARTNERSHIP', 'Farm Services'), ('SOLE PROPRIETOR', 'Sole Proprietor')], max_length=255, null=True),
        ),
    ]
